-- Create charm_usage table to track charm purchases and usage
CREATE TABLE IF NOT EXISTS charm_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  charm_id VARCHAR(255) NOT NULL,
  times_purchased INTEGER DEFAULT 0,
  times_generated INTEGER DEFAULT 0, -- Generated by Generator charm or other means
  times_copied INTEGER DEFAULT 0, -- Copied by Paranoia or other means
  first_purchased_at TIMESTAMP,
  last_purchased_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, charm_id)
);

-- Create index for fast user lookups
CREATE INDEX IF NOT EXISTS idx_charm_usage_user_id ON charm_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_charm_usage_charm_id ON charm_usage(charm_id);

-- Create trigger to update updated_at timestamp
DROP TRIGGER IF EXISTS update_charm_usage_updated_at ON charm_usage;
CREATE TRIGGER update_charm_usage_updated_at
  BEFORE UPDATE ON charm_usage
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

